### ISSUE TITLE
create_dataset.py

### ISSUE THREAD

**Issue by PythonImageDeveloper** [sshleifer/object_detection_kitti#3]
hi
when i run python create_dataset.py , i get this error : ImportError: No module named 'object_detection.kitti_to_voc'
i have this module my directory . and i followed tree kitti_dataset , this is ok , but i dont know that error what is it ?

**Comment by sshleifer** [comment]
Dont know windows well, but i would guess problem is with PYTHONPATH
What is your pythonpath, where are you running code from?

**Comment by PythonImageDeveloper** [comment]
no i switch to ubuntu 16.04 , i running this code from object_detection folder with command python3 create_dataset.py
in this folder i have kitti_data

**Comment by sshleifer** [comment]
Hmm. can you paste a traceback?

**Comment by PythonImageDeveloper** [comment]
mm@mm:~/object_detection_kitti-master/object_detection$  python3 create_dataset.py 
Traceback (most recent call last):
  File "create_dataset.py", line 16, in <module>
    from object_detection.kitti_to_voc import kitti_to_voc
ImportError: No module named 'object_detection.kitti_to_voc'

**Comment by PythonImageDeveloper** [comment]
Hi sshleife
this code don't work .  ImportError: No module named 'object_detection.kitti_to_voc'
please step by step go through. and ubuntu 16 or 14 ?

**Comment by PythonImageDeveloper** [comment]
is this correct ? 

mm@mm:~/object_detection_kitti/object_detection$ python3 create_dataset.py 
Traceback (most recent call last):
  File "create_dataset.py", line 182, in <module>
    do_kitti_ingest()
  File "/home/mm/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mm/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mm/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mm/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "create_dataset.py", line 173, in do_kitti_ingest
    VOC_TRAIN_DIR, os.path.join(data_dir, 'train.txt'))
  File "/home/mm/object_detection_kitti/object_detection/kitti_to_voc.py", line 15, in kitti_to_voc
    train_ids=train_id_path)
  File "/home/mm/object_detection_kitti/object_detection/vod_converter/converter.py", line 136, in convert
    image_detections = ingestor.ingest(from_path, train_ids)
  File "/home/mm/object_detection_kitti/object_detection/vod_converter/kitti.py", line 64, in ingest
    image_ext = self.find_image_ext(path, first_image_id)
  File "/home/mm/object_detection_kitti/object_detection/vod_converter/kitti.py", line 74, in find_image_ext
    raise Exception("could not find jpg or png for %s at %s/image_2" % (image_id, root))
Exception: could not find jpg or png for 000000
000001
000002
000003
[................................]
007477
007478
007479
007480 at kitti_data/training/image_2

why can't create tfrecord ?

what are these ? I got confused . what did you do ? why VOC ? 
VOC_TRAIN_DIR = 'voc_kitti'
VOC_VALID_DIR = 'voc_kitti_valid'

**Comment by sshleifer** [comment]
Yeah!

**Comment by PythonImageDeveloper** [comment]
So what do i do then؟

**Comment by sshleifer** [comment]
what does echo $PATH in terminal produce?

**Comment by ghimiremukti** [comment]
I think the problem is that root directory is not in PYTHONPATH. put it and try running. e.g.

$ export PYTHONPATH=absolute-path-to-repo/object_detection_kitti:$PYTHONPATH
$ source .bashrc

CLUE:
absolute-path-to-repo/object_detection_kitti directory contains adv_imagenet_models, adversarial_crypto....etc.

Hi @sshleifer , could you plz take a look on other issue I just created. Thanks in advance.
